### ISSUE TITLE
Rfbrowser init fails downloading chromium (Logger seems to be at fault)

### ISSUE THREAD

**Issue by TimDicos** [MarketSquare/robotframework-browser#2083]
**Bug-Description**
When trying to execute
"rfbrowser init"
the following Stacktrace is printed into the console:

File “C:\ManualInstall\python\lib\runpy.py”, line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File “C:\ManualInstall\python\lib\runpy.py”, line 87, in run_code
exec(code, run_globals)
File "C:\ManualInstall\python\Scripts\rfbrowser.exe_main.py", line 7, in
File “C:\ManualInstall\python\lib\site-packages\Browser\entry.py”, line 237, in run
rfbrowser_init(args.skip_browsers)
File “C:\ManualInstall\python\lib\site-packages\Browser\entry.py”, line 53, in rfbrowser_init
raise error
File “C:\ManualInstall\python\lib\site-packages\Browser\entry.py”, line 45, in rfbrowser_init
_rfbrowser_init(skip_browser_install, install_file)
File “C:\ManualInstall\python\lib\site-packages\Browser\entry.py”, line 149, in _rfbrowser_init
log_file.write(output)
File “C:\ManualInstall\python\lib\encodings\cp1252.py”, line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: ‘charmap’ codec can’t encode characters in position 1-8: character maps to 

**Reproduction**
Establish the following setup:

1. Windows 10 Pro (64-bit)
2. Python 3.9.13
3. pip 22.1.1
4. pip:robotframework (Python 3.9.13 on win32)
5. pip:robotframework:browser 12.4.0

run in *cmd*:
rfbrowser init

**Expected behavior**
robotframework setup executes and the appropriate drivers are installed

**Additional context**
Post 3918 in the Robotframework-Forum
[Add any other context about the problem here.](https://forum.robotframework.org/t/rfbrowser-init-fails-downloading-chromium/3918)

**Comment by TimDicos** [comment]
@jefftrigueiro 
Do you have the same OS and setup as described above?

**Comment by jefftrigueiro** [comment]
@TimDicos 
- Windows 10 pro (64-bits)
- Python 3.9.2
- pip 22.1.2
- Robot Framework 5.0.1 (Python 3.9.2 on win32)
- robotframework-browser 13.1.0

**Comment by aaltat** [comment]
I could not reproduce the issue, but I see from the stack trace what causes the failure. But because I can not reproduce the issue, I am not sure does my fix, in #2104, actually fix the issue. Therefore if you are still able to reproduce the problem, could you do `pip install robotframework-browser` and before you run `rfbrowser init`, could you replace [entry.py](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/entry.py) in your installation. All feedback is appreciated, thank you.

**Comment by martinwlp** [comment]
@aaltat 

Issue is still occurring. It crashes on the chromium download as previously described.
So it seems to be happening on any machine with the first install of browser.

This is a blocker. Nobody can install browser during a first time installation.

**Comment by aaltat** [comment]
Would it be possible to see the `rfbrowser.log` log file from your Browser library installation directory?

**Comment by martinwlp** [comment]
As requested:
[rfbrowser (2).log](https://github.com/MarketSquare/robotframework-browser/files/8909884/rfbrowser.2.log)

**Comment by aaltat** [comment]
That looks like the it's not using the latest changes, did you remember to replace the file?

**Comment by martinwlp** [comment]
Hi @aaltat ,

When replacing the entry.py a different error occurs, see below a snippet from the cmd terminal:

C:\Users\XXX>rfbrowser init
Traceback (most recent call last):
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\XXX\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\Scripts\rfbrowser.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'run' from 'Browser.entry' (c:\users\XXX\appdata\local\programs\python\python39\lib\site-packages\Browser\entry.py)

**Comment by martinwlp** [comment]
@aaltat - any thoughts on above error ? 
This issue has been reproduced on 2 of our QA engineers machines. Blocking them from using Browser.
Appreciate your help,
Thanks,

**Comment by martinwlp** [comment]
reinstalling node and robotframework-browser has resolved our issue.

**Comment by TimDicos** [comment]
@aaltat 
I updated Browser according with the update instructions on the main github readme:
`pip install -U robotframework-browser`
`rfbrowser clean-node`
`rfbrowser init`
This still produces the same error:

Traceback (most recent call last):
  File "C:\ManualInstall\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ManualInstall\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ManualInstall\python\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 237, in run
    rfbrowser_init(args.skip_browsers)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 53, in rfbrowser_init
    raise error
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 45, in rfbrowser_init
    _rfbrowser_init(skip_browser_install, install_file)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 149, in _rfbrowser_init
    log_file.write(output)
  File "C:\ManualInstall\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-8: character maps to <undefined>

---------

Replacing the entry.py in `[...]\python\Lib\site-packages\Browser` yield the an error as reported by **marinwlp**:

Traceback (most recent call last):
  File "C:\ManualInstall\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ManualInstall\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ManualInstall\python\Scripts\rfbrowser.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'run' from 'Browser.entry' (C:\ManualInstall\python\lib\site-packages\Browser\entry.py)

---------

As for reinstalling node and robotframework:
I am quite reluctant mess with my current installation of robotframework because I am actively using it. (Even tho unwillingly with selenium instead of playwright.)
Removing node is even more daunting as I can't really afford to mess up my setup under my current workload. ^^'

**Comment by TimDicos** [comment]
@aaltat 
Can you reopen the issue? It's still a problem on my machine x)

**Comment by aaltat** [comment]
Can you show me new stack trace, code has changed and it should fail differently with the new release.

**Comment by andreagubellini** [comment]
We are facing the same issue when trying to build the image. We tried with both versions 13.2.0, 13.1.0 and 13.0.0.

The error we get is:

```
Traceback (most recent call last):
  File "/home/pwuser/.local/bin/rfbrowser", line 5, in <module>
    from Browser.entry import main
ImportError: cannot import name 'main' from 'Browser.entry' (/usr/local/lib/python3.8/dist-packages/Browser/entry.py)
```

**Comment by TimDicos** [comment]
@aaltat
Thanks a lot for reopening the issue. :)
The update certainly did someting.  "rfbrowser init" now complets, but not without repeatedly printing a pretty similar error message to before. I guess you prevented it from instantly failing on the first encoding error, so it managed to encounter it quite a few times.

The following two login errors are the first of ~40 similar ones that get logged. I included them as an excerpt. I will append the full console log.

C:\>rfbrowser init
2022-06-30 09:53:04,600 [INFO    ] ==============================================================================================================
2022-06-30 09:53:04,600 [INFO    ] Installing node dependencies...
2022-06-30 09:53:04,616 [INFO    ] Installing rfbrowser node dependencies at C:\ManualInstall\python\lib\site-packages\Browser\wrapper
2022-06-30 09:53:09,089 [INFO    ]

2022-06-30 09:53:09,089 [INFO    ] > playwright@1.22.2 install C:\ManualInstall\python\lib\site-packages\Browser\wrapper\node_modules\playwright

2022-06-30 09:53:09,089 [INFO    ] > node install.js

2022-06-30 09:53:09,089 [INFO    ]

2022-06-30 09:53:09,390 [INFO    ] Downloading Chromium 102.0.5005.40 (playwright build v1005)...

2022-06-30 09:53:09,443 [INFO    ] |                                                                                |   0% of 104.1 Mb

--- Logging error ---
Traceback (most recent call last):
  File "C:\ManualInstall\python\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\ManualInstall\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-43: character maps to <undefined>
Call stack:
  File "C:\ManualInstall\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ManualInstall\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ManualInstall\python\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 256, in main
    runner(command, skip_browsers, trace_file)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 201, in runner
    rfbrowser_init(skip_browsers)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 49, in rfbrowser_init
    _rfbrowser_init(skip_browser_install)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 153, in _rfbrowser_init
    logging.info(output)
Message: '|■■■■■■■■                                                                        |  10% of 104.1 Mb\n'
Arguments: ()
2022-06-30 09:53:10,514 [INFO    ] |■■■■■■■■                                                                        |  10% of 104.1 Mb

--- Logging error ---
Traceback (most recent call last):
  File "C:\ManualInstall\python\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\ManualInstall\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-51: character maps to <undefined>
Call stack:
  File "C:\ManualInstall\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ManualInstall\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ManualInstall\python\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 256, in main
    runner(command, skip_browsers, trace_file)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 201, in runner
    rfbrowser_init(skip_browsers)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 49, in rfbrowser_init
    _rfbrowser_init(skip_browser_install)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 153, in _rfbrowser_init
    logging.info(output)
Message: '|■■■■■■■■■■■■■■■■                                                                |  20% of 104.1 Mb\n'
Arguments: ()
2022-06-30 09:53:11,601 [INFO    ] |■■■■■■■■■■■■■■■■                                                                |  20% of 104.1 Mb

----------

[log.txt](https://github.com/MarketSquare/robotframework-browser/files/9017682/log.txt)

**Comment by aaltat** [comment]
Ok, now I see.  Need to look can those progress bars and other funny characters suppressed on node side or do I need to some characters encoding. I am hoping that first one is possible,  because later one is hard to do.

**Comment by aaltat** [comment]
Because I can not reproduce the problem, could you change [line](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/entry.py#L143) from `npm ci --production",` to `"npm ci --production --parseable true --progress false",` and see does it fix the problem?

**Comment by aaltat** [comment]
Fixed again with https://github.com/MarketSquare/robotframework-browser/pull/2152

**Comment by aaltat** [comment]
There has been two fixes and the latest one is not yet released.

**Comment by TimDicos** [comment]
@aaltat 
I am still seeing the stacktraces in the console but "rfbrowser init" now complets and I can utilize the library in my RFW-setup. Thanks a lot. :)

**Comment by aaltat** [comment]
Could you show us the stack trace?

**Comment by TimDicos** [comment]
Gotta say: I was quite hesitant to touch the installation after we got it running, but I think it#s the least I can do. 😄 

Here is a sample stacktrace and the full log is appended:
`
--- Logging error ---
Traceback (most recent call last):
  File "C:\ManualInstall\python\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\ManualInstall\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-43: character maps to <undefined>
Call stack:
  File "C:\ManualInstall\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ManualInstall\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ManualInstall\python\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 259, in main
    runner(command, skip_browsers, trace_file)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 204, in runner
    rfbrowser_init(skip_browsers)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 49, in rfbrowser_init
    _rfbrowser_init(skip_browser_install)
  File "C:\ManualInstall\python\lib\site-packages\Browser\entry.py", line 154, in _rfbrowser_init
    logging.info(output)
`
Full Log:
[log.txt](https://github.com/MarketSquare/robotframework-browser/files/9209307/log.txt)

**Comment by Sandeep-QA** [comment]
@andreagubellini Were you able to resolve the issue mentioned here? I got below error in robotframework-browser==13.1.0
```
Initializing library 'Browser' with arguments [ strict=False | run_on_failure=take screenshot on test failure | jsextension=/TestSuite/AWS-NV/FE-Suite/Platform/tests/platform/../../scripts/jsextension/index.js ] failed: TypeError: Formatter() takes no arguments
09:58:32  Traceback (most recent call last):
09:58:32    File "/usr/local/lib/python3.8/dist-packages/Browser/browser.py", line 729, in __init__
09:58:32      Formatter(self),
09:58:32  TypeError: Formatter() takes no arguments
```
On updating to robotframework-browser==13.4.0 getting below error in jenkins. Any idea how to resolve this?

```
File "/home/pwuser/.local/bin/rfbrowser", line 5, in <module>
  from Browser.entry import run
  ImportError: cannot import name 'run' from 'Browser.entry' (/usr/local/lib/python3.8/dist-packages/Browser/entry.py)

```

> We are facing the same issue when trying to build the image. We tried with both versions 13.2.0, 13.1.0 and 13.0.0.
> 
> The error we get is:
> 
> ```
> Traceback (most recent call last):
>   File "/home/pwuser/.local/bin/rfbrowser", line 5, in <module>
>     from Browser.entry import main
> ImportError: cannot import name 'main' from 'Browser.entry' (/usr/local/lib/python3.8/dist-packages/Browser/entry.py)
> ```
